import type { Metadata } from "next";
import "./globals.css";
import NavbarWrapper from "@/UI/NavBarWrapper";
import Footer from "@/UI/Footer";

export const metadata: Metadata = {
  title: "Fasco Runway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
        />
      </head>
      <body className="antialiased">
        <NavbarWrapper />
        {children}
        <Footer />
        <div id="portal-root" />
      </body>
    </html>
  );
}